import type { MetadataRoute } from "next";

/**
 * robots.txt, generated by Next.js at /robots.txt.
 * The site had no robots file and no sitemap until September 2026, which
 * left the index holding stale URLs from the old /project/ scheme.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: "https://shawncapizzi.com/sitemap.xml",
  };
}
