import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

/**
 * robots.txt, generated by Next.js at /robots.txt.
 *
 * Policy (September 2026): every crawler is welcome, including the ones AI
 * companies use for training. The answer-engine crawlers are also named on
 * their own so the intent is on record. A crawler that matches a named group
 * ignores the * group, so each named group repeats the same rules.
 *
 * Sources for the names, checked September 2026:
 *   OpenAI:     developers.openai.com/api/docs/bots
 *   Anthropic:  support.claude.com/en/articles/8896518
 *   Perplexity: docs.perplexity.ai/docs/resources/perplexity-crawlers
 *
 * /api/ holds only the newsletter endpoint, which has nothing to index.
 */

const ANSWER_ENGINES = [
  "OAI-SearchBot",
  "ChatGPT-User",
  "Claude-SearchBot",
  "Claude-User",
  "PerplexityBot",
  "Perplexity-User",
];

export default function robots(): MetadataRoute.Robots {
  const rules = { allow: "/", disallow: "/api/" };
  return {
    rules: [
      { userAgent: "*", ...rules },
      { userAgent: ANSWER_ENGINES, ...rules },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
