import type { MetadataRoute } from "next";

/**
 * sitemap.xml, generated by Next.js at /sitemap.xml.
 *
 * Every route listed here exists under /app as a page.tsx. When a page is
 * added or removed, update this list in the same commit. Routes that are
 * noindex (private outreach pages) do not belong here.
 */

const BASE = "https://shawncapizzi.com";

const ROUTES: { path: string; priority: number }[] = [
  { path: "/", priority: 1.0 },
  { path: "/work", priority: 0.9 },
  { path: "/work/pharma-design-systems", priority: 0.8 },
  { path: "/work/cancer-equality-app", priority: 0.8 },
  { path: "/work/courtvisual", priority: 0.8 },
  { path: "/work/enterprise-financial-services-crm", priority: 0.7 },
  { path: "/work/multi-brand-pharma-sales-tools", priority: 0.7 },
  { path: "/work/ai-native-product-design-lab", priority: 0.7 },
  { path: "/work/vui-voice-pill-tracker", priority: 0.5 },
  { path: "/engagements", priority: 0.9 },
  { path: "/clarity-advantage", priority: 0.7 },
  { path: "/book/chapter-1", priority: 0.6 },
  { path: "/thinking", priority: 0.6 },
  { path: "/about", priority: 0.6 },
  { path: "/faq", priority: 0.5 },
  { path: "/contact", priority: 0.7 },
  { path: "/privacy", priority: 0.2 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ROUTES.map(({ path, priority }) => ({
    url: `${BASE}${path}`,
    lastModified,
    changeFrequency: "monthly",
    priority,
  }));
}
