// Destination: lib/clarity-cards.ts
// Canonical Clarity Cards data (adult deck), generated from adult.json.
// 54 cards: Clarity (♠), Audience (♥), Action (♦), System (♣) at 13 each
// (A-K), plus two Wildcards (J1, J2 = ★). House style: no em dashes.

export type ClaritySuit =
  | "Clarity"
  | "Audience"
  | "Action"
  | "System"
  | "Wildcard";

export interface ClarityCard {
  /** Sequential card number, 1-54. */
  number: number;
  suit: ClaritySuit;
  /** Unicode suit glyph: ♠ ♥ ♦ ♣ ★ */
  suitSymbol: string;
  pillar: string;
  /** Playing-card rank: "A", "2"-"10", "J", "Q", "K", or "J1"/"J2" (wildcards). */
  rank: string;
  title: string;
  /** Large front prompt (the question). */
  prompt: string;
  /** Small front clarifier (one-line context). */
  clarifier: string;
  bestUsedWhen: string;
}

export const CLARITY_CARDS: ClarityCard[] = [
  {
    number: 1,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "A",
    title: "Clarity",
    prompt: "What's actually stuck?",
    clarifier: "Before you brief the design, name the actual blocker: political, technical, strategic, or unclear scope.",
    bestUsedWhen: "Pull at the start of any project where the team feels misaligned about what they're solving.",
  },
  {
    number: 2,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "2",
    title: "The Real Problem",
    prompt: "What problem is this actually solving?",
    clarifier: "Strip away the request and ask what the underlying need is. The brief is rarely the brief.",
    bestUsedWhen: "Pull when you've been handed a deliverable but the goal is unclear.",
  },
  {
    number: 3,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "3",
    title: "Two Sentences",
    prompt: "Can you state the problem in two sentences?",
    clarifier: "If you can't, you don't have a problem statement: you have a problem feeling.",
    bestUsedWhen: "Pull when scope keeps expanding and the team can't agree on what 'done' means.",
  },
  {
    number: 4,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "4",
    title: "The Real Goal",
    prompt: "What does success look like in 90 days?",
    clarifier: "If the answer is vague, the team is optimizing for activity, not outcomes.",
    bestUsedWhen: "Pull when the team is producing a lot but the business hasn't moved.",
  },
  {
    number: 5,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "5",
    title: "Hidden Assumption",
    prompt: "What are we assuming that nobody's said out loud?",
    clarifier: "Surface the unspoken assumptions. They're usually where the real disagreement lives.",
    bestUsedWhen: "Pull when consensus feels too easy or stakeholders keep contradicting their own briefs.",
  },
  {
    number: 6,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "6",
    title: "The Actual User",
    prompt: "Are we designing for the user or the stakeholder reviewing this?",
    clarifier: "Most enterprise design optimizes for the approver, not the person who'll use it.",
    bestUsedWhen: "Pull when reviews keep changing direction without new user evidence.",
  },
  {
    number: 7,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "7",
    title: "Cost of Wrong",
    prompt: "What happens if we get this wrong?",
    clarifier: "If nothing happens, this isn't worth designing carefully. If a lot happens, slow down.",
    bestUsedWhen: "Pull when the team is moving fast but the stakes haven't been named.",
  },
  {
    number: 8,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "8",
    title: "Timeline Truth",
    prompt: "Is the deadline real, or is it political?",
    clarifier: "Real deadlines have external consequences. Political deadlines are leverage.",
    bestUsedWhen: "Pull when the timeline is driving decisions you wouldn't otherwise make.",
  },
  {
    number: 9,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "9",
    title: "What's Off Limits",
    prompt: "What can't we change, and why?",
    clarifier: "Constraints aren't always real. Sometimes they're inherited assumptions worth challenging.",
    bestUsedWhen: "Pull when the team accepts a constraint that's making the work worse.",
  },
  {
    number: 10,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "10",
    title: "The Yes/No Test",
    prompt: "Can a stakeholder give us a clear yes or no on this?",
    clarifier: "If they can only say 'maybe' or 'it depends,' the question isn't sharp enough.",
    bestUsedWhen: "Pull before any executive review. Sharpen the asks first.",
  },
  {
    number: 11,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "J",
    title: "The Workshop Reset",
    prompt: "If we walked out of this room with one decision, what would it be?",
    clarifier: "Workshops produce alignment when they produce decisions, not artifacts.",
    bestUsedWhen: "Pull at the start or middle of any workshop. Forces priority.",
  },
  {
    number: 12,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "Q",
    title: "What Would Stop This",
    prompt: "What would have to be true for this not to work?",
    clarifier: "Inverting the question surfaces blockers faster than asking 'what would help?'",
    bestUsedWhen: "Pull during planning. The answers become your real risk register.",
  },
  {
    number: 13,
    suit: "Clarity",
    suitSymbol: "♠",
    pillar: "The Real Problem",
    rank: "K",
    title: "The Brief Behind the Brief",
    prompt: "What's the brief your stakeholder didn't write down?",
    clarifier: "Senior briefs always have a hidden context: politics, fear, ambition. Find it.",
    bestUsedWhen: "Pull when you're the senior in the room and need to lead the conversation.",
  },
  {
    number: 14,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "A",
    title: "Audience",
    prompt: "When did you last actually talk to a user?",
    clarifier: "Not a survey. Not analytics. A real conversation. If it's been more than 90 days, the work is guessing.",
    bestUsedWhen: "Pull at the start of any project, especially one based on existing assumptions.",
  },
  {
    number: 15,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "2",
    title: "Who Is This For",
    prompt: "Can you describe one specific user in one sentence?",
    clarifier: "If the description is generic ('our customers'), the work will be too.",
    bestUsedWhen: "Pull when audience definitions feel abstract or universal.",
  },
  {
    number: 16,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "3",
    title: "Mental Model",
    prompt: "What does the user think they're doing here?",
    clarifier: "Their mental model rarely matches the IA you've built. The gap is the work.",
    bestUsedWhen: "Pull when navigation feels obvious to the team but confusing to users.",
  },
  {
    number: 17,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "4",
    title: "Trust Threshold",
    prompt: "What does this user need to believe before they'll take action?",
    clarifier: "Action without trust doesn't convert. Trust comes before the CTA.",
    bestUsedWhen: "Pull when conversion is low despite clear CTAs.",
  },
  {
    number: 18,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "5",
    title: "Three Questions",
    prompt: "What three questions does this user have before they'll engage?",
    clarifier: "If the page doesn't answer them in the first scroll, the user leaves.",
    bestUsedWhen: "Pull when redesigning a hero or landing experience.",
  },
  {
    number: 19,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "6",
    title: "Fear Factor",
    prompt: "What is this user afraid of?",
    clarifier: "Especially in regulated contexts: patients fear bias, investors fear loss, HCPs fear liability.",
    bestUsedWhen: "Pull in healthcare, financial, and high-stakes UX work.",
  },
  {
    number: 20,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "7",
    title: "What They Already Know",
    prompt: "What does this user already know about us?",
    clarifier: "Don't repeat things they know. Build on them.",
    bestUsedWhen: "Pull when content feels redundant or condescending in user testing.",
  },
  {
    number: 21,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "8",
    title: "First Time vs. Returning",
    prompt: "Are we designing for first-time or returning users?",
    clarifier: "These are two different products. Don't pretend it's one.",
    bestUsedWhen: "Pull in product onboarding or marketing site work.",
  },
  {
    number: 22,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "9",
    title: "Who Holds the Decision",
    prompt: "In their world, who else is in the decision?",
    clarifier: "Most B2B and healthcare users aren't deciding alone. Who else are they convincing?",
    bestUsedWhen: "Pull in B2B, enterprise, and HCP-targeted work.",
  },
  {
    number: 23,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "10",
    title: "Where They Started",
    prompt: "Where did this user come from before they got here?",
    clarifier: "Their entry context shapes their attention, expectation, and emotional state.",
    bestUsedWhen: "Pull in journey mapping or attribution work.",
  },
  {
    number: 24,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "J",
    title: "The Caregiver Question",
    prompt: "Is the person seeing this the same person making the decision?",
    clarifier: "In healthcare especially, the patient and the decision-maker are often different people.",
    bestUsedWhen: "Pull in patient-facing and healthcare experience design.",
  },
  {
    number: 25,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "Q",
    title: "The Real Voice",
    prompt: "What words does this user actually use?",
    clarifier: "If your copy uses words your user doesn't, the search and trust both break.",
    bestUsedWhen: "Pull when content is being written in agency or brand voice instead of user voice.",
  },
  {
    number: 26,
    suit: "Audience",
    suitSymbol: "♥",
    pillar: "Knowing the User",
    rank: "K",
    title: "The User After This",
    prompt: "What does this user want to do next?",
    clarifier: "The end of one experience is the start of another. Design for the handoff.",
    bestUsedWhen: "Pull when designing a flow's exit, not just its entry.",
  },
  {
    number: 27,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "A",
    title: "Action",
    prompt: "What's the one action that matters most?",
    clarifier: "If the page has more than three CTAs, none of them is the most important. Pick one.",
    bestUsedWhen: "Pull when reviewing any conversion-focused experience.",
  },
  {
    number: 28,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "2",
    title: "HVA over CTA",
    prompt: "What's the high-value action behind the CTA?",
    clarifier: "A CTA is a button. An HVA is the behavior that creates business value. Don't confuse them.",
    bestUsedWhen: "Pull when a CTA exists but the team can't articulate why it matters.",
  },
  {
    number: 29,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "3",
    title: "Distraction Audit",
    prompt: "What's competing with the primary action on this page?",
    clarifier: "Every secondary element costs the primary action attention. Cut what doesn't earn its place.",
    bestUsedWhen: "Pull during page reviews when conversion is below target.",
  },
  {
    number: 30,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "4",
    title: "First Action",
    prompt: "What's the first action a user can take that creates value?",
    clarifier: "Smaller, faster wins beat asking for a full commitment up front.",
    bestUsedWhen: "Pull in onboarding, lead capture, and trial design.",
  },
  {
    number: 31,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "5",
    title: "Time to Value",
    prompt: "How long until this user gets value from us?",
    clarifier: "Senior buyers count this in seconds, not minutes. Move it earlier.",
    bestUsedWhen: "Pull when product or marketing experiences feel slow to land.",
  },
  {
    number: 32,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "6",
    title: "What We're Not Asking For",
    prompt: "What action are we NOT asking for, and why not?",
    clarifier: "Sometimes the right move is to remove an ask, not add one. The page converts more.",
    bestUsedWhen: "Pull when adding a CTA seems obvious. Question whether it should exist at all.",
  },
  {
    number: 33,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "7",
    title: "Action Hierarchy",
    prompt: "If a user can only do one thing here, what is it?",
    clarifier: "The hierarchy of the page should match the hierarchy of the actions.",
    bestUsedWhen: "Pull when visual hierarchy and action priority don't line up.",
  },
  {
    number: 34,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "8",
    title: "Conversion vs. Adoption",
    prompt: "Are we measuring conversion or adoption?",
    clarifier: "Conversion is one event. Adoption is sustained behavior. Different design choices.",
    bestUsedWhen: "Pull when metrics are being defined or contested.",
  },
  {
    number: 35,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "9",
    title: "Friction Audit",
    prompt: "What's the friction between intent and action here?",
    clarifier: "Reducing friction beats adding persuasion. Find the steps that don't earn their place.",
    bestUsedWhen: "Pull during flow analysis or A/B test planning.",
  },
  {
    number: 36,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "10",
    title: "The Compound Action",
    prompt: "What's the second thing that should happen after this action?",
    clarifier: "One conversion is just the start. Design the second action immediately.",
    bestUsedWhen: "Pull during journey design and lifecycle planning.",
  },
  {
    number: 37,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "J",
    title: "Measurement Truth",
    prompt: "Can we actually measure whether this worked?",
    clarifier: "If you can't measure it, you can't claim it worked. Build measurement before launch.",
    bestUsedWhen: "Pull during scoping. Before deliverables are defined.",
  },
  {
    number: 38,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "Q",
    title: "Cost of Action",
    prompt: "What's it costing the user to take this action?",
    clarifier: "Time, mental load, trust, money, identity exposure. Every action has a cost.",
    bestUsedWhen: "Pull when conversion rates feel inexplicably low.",
  },
  {
    number: 39,
    suit: "Action",
    suitSymbol: "♦",
    pillar: "High-Value Action",
    rank: "K",
    title: "The Action That Compounds",
    prompt: "Which action, repeated, creates exponential value?",
    clarifier: "Compound actions (refer, share, return, save) beat one-time actions in lifetime value.",
    bestUsedWhen: "Pull during product strategy and roadmap planning.",
  },
  {
    number: 40,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "A",
    title: "System",
    prompt: "What happens when someone outside this room uses this?",
    clarifier: "Designs that only work with their authors don't scale. Test for the strangers.",
    bestUsedWhen: "Pull during design system, template, or governance work.",
  },
  {
    number: 41,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "2",
    title: "The Second Use",
    prompt: "What does this look like the second time someone needs to use it?",
    clarifier: "First-use design is performance. Second-use design is product.",
    bestUsedWhen: "Pull when something feels great in demo but unclear in use.",
  },
  {
    number: 42,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "3",
    title: "Brand Team Test",
    prompt: "Can a brand team customize this without breaking it?",
    clarifier: "Modular systems give brands flexibility within governance. Rigid systems get bypassed.",
    bestUsedWhen: "Pull during multi-brand design system work.",
  },
  {
    number: 43,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "4",
    title: "Maintenance Math",
    prompt: "Who maintains this in 18 months?",
    clarifier: "If the answer is 'we don't know,' the system will fragment.",
    bestUsedWhen: "Pull during system handoff or governance design.",
  },
  {
    number: 44,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "5",
    title: "Pattern vs. One-Off",
    prompt: "Is this a pattern, or is this a one-off?",
    clarifier: "Treating one-offs as patterns creates rigidity. Treating patterns as one-offs creates fragmentation.",
    bestUsedWhen: "Pull during component or content audit.",
  },
  {
    number: 45,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "6",
    title: "Documentation Test",
    prompt: "Could a new team member ship using this with no meeting?",
    clarifier: "If the documentation requires a Slack thread, the documentation isn't done.",
    bestUsedWhen: "Pull during system delivery or after onboarding new team members.",
  },
  {
    number: 46,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "7",
    title: "Decision Log",
    prompt: "Is the reason for this decision findable in 6 months?",
    clarifier: "Decisions without context get re-litigated forever. Document the why, not just the what.",
    bestUsedWhen: "Pull during system documentation and architecture decisions.",
  },
  {
    number: 47,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "8",
    title: "Governance Without Bureaucracy",
    prompt: "What's the lightest possible review that still protects quality?",
    clarifier: "Heavy governance gets routed around. Light governance with clear stakes gets used.",
    bestUsedWhen: "Pull when teams resist a system or skip approval steps.",
  },
  {
    number: 48,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "9",
    title: "Reuse Test",
    prompt: "Can this be used for the next brand without rebuild?",
    clarifier: "True systems scale. False systems require rework on each new use.",
    bestUsedWhen: "Pull during the second deployment of any framework or pattern.",
  },
  {
    number: 49,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "10",
    title: "Tech Debt Audit",
    prompt: "What are we doing now that future-you will hate?",
    clarifier: "Surface technical debt while it's still cheap to address.",
    bestUsedWhen: "Pull during sprint planning and architectural reviews.",
  },
  {
    number: 50,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "J",
    title: "The Hand-Off",
    prompt: "Who picks this up after we ship?",
    clarifier: "Most enterprise work fails at the hand-off, not at the launch.",
    bestUsedWhen: "Pull before any project closure or transition.",
  },
  {
    number: 51,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "Q",
    title: "Modular vs. Monolithic",
    prompt: "Are the parts of this independently usable?",
    clarifier: "Modular components flex. Monolithic ones break when context shifts.",
    bestUsedWhen: "Pull during component, content, or system architecture decisions.",
  },
  {
    number: 52,
    suit: "System",
    suitSymbol: "♣",
    pillar: "Scale & Governance",
    rank: "K",
    title: "The System Still Standing",
    prompt: "Will this still work when half the team is gone?",
    clarifier: "Resilient systems survive turnover. Fragile ones don't.",
    bestUsedWhen: "Pull during system maturity reviews and risk assessments.",
  },
  {
    number: 53,
    suit: "Wildcard",
    suitSymbol: "★",
    pillar: "Joker",
    rank: "J1",
    title: "AI Reality Check",
    prompt: "Is the AI actually solving a problem we have, or one a vendor sold us?",
    clarifier: "Most AI implementations skip the foundational work. Most vendors don't bring it up. Yours has to.",
    bestUsedWhen: "Pull when AI is being added to a roadmap, brief, or strategy without clear user-grounded rationale.",
  },
  {
    number: 54,
    suit: "Wildcard",
    suitSymbol: "★",
    pillar: "Joker",
    rank: "J2",
    title: "Stop and Reset",
    prompt: "If we walked out of this room and started over, what would we do differently?",
    clarifier: "Sometimes the best move is to admit the path is wrong and reset.",
    bestUsedWhen: "Pull when the team is grinding without progress, or when sunk costs are driving decisions.",
  },
];
